import express, { Request, Response } from 'express';
import bodyParser from 'body-parser';
import { RegisterRoutes } from '@build/routes'; // This will be generated by tsoa
import db from "@src/db";
import config from "@src/config";
import swaggerUi from 'swagger-ui-express'

const createApp = (async () => {
  
  const app = express();
  
  await db.authenticate();
  await db.sync();
  
  app.use(bodyParser.json());

  // Swagger
  app.use('/docs', swaggerUi.serve, async (_: Request, res: Response) => {
    const spec = await import('../build/swagger.json', { assert: { type: 'json' } })

    return res.send(swaggerUi.generateHTML(spec.default))
  })

  // Register our generated routes
  RegisterRoutes(app);
  
  app.listen(config.port, () => {
    console.log('Server is running on port 3000.');
  });

  return app;
});

export default createApp();